---
title: "Git, Github"
author: "Ben Best"
date: "October 1, 2014"
output: 
  html_document:
    toc: true
---


## git bash

Go to Windows button and start typing "Git Bash" (and enter) to launch program.

### Setup Git user

```bash
git config --global user.name "Ben Best"
git config --global user.email bbest@nceas.ucsb.edu
```

You can confirm that these variables are properly set:

```bash
git config --global --list
```

### navigating Git bash

Comments preceeded with `#`.

```bash
# list files and folders
ls

# show present working directory
pwd

# make directory to store your github repositories
mkdir github

# change directory to github
cd github

# clone the class repository
git clone git@github.com:ucsb-bren/esm296-4f.git

# change directory back to home, ie H: drive
cd ~
```

### copy / paste in bash window

To paste, right click on top bar of window > Edit > Paste.

To copy, 

### clone [esm296-4f]

git clone https://github.com/ucsb-bren/esm296-4f

git@github.com:bbest/courses.git

### setup rstudio [esm296-4f]

Tools > Global Options...

- Git/SVN > Git executable: Browse... and paste `C:\Program Files (x86)\Git\bin\git.exe`

- R General
    - untick: Restore .Rdata into workspace at startup
    - Save workspace to .RData on exit: Never
    
- OK, and restart RStudio

File > New Project...
Version Control > Git > 

https://github.com/bbest/courses.git


## file srxr

- H:/
    - R/
    - github/
        - esm296-4f/ course repo
        - courses/   personal repo
            - esm296-4f/
    - esm296-4f/  workspace, especially for big data files


## github setup

- invite profs: bbest, frew, lwedding?
- create an issue

## git setup

[master 0c8e9e3] adding R setup
 Committer: unknown <bbest_student@frew-test.esm.ucsb.edu>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:


After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 17 insertions(+)
 create mode 100644 wk01_programming/setup_r.R
